[package]
name = "mercutio"
description = "IO-less MCP server library"
version = "0.9.0-alpha.1"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mbr/mercutio-rs"
documentation = "https://docs.rs/mercutio"

[features]
io-stdlib = []
io-tokio = ["dep:tokio"]
io-axum = ["dep:axum", "dep:tokio", "rand"]
jiff = ["dep:jiff"]
chrono = ["dep:chrono"]
cli = ["dep:clap"]

[package.metadata.docs.rs]
features = ["cli", "io-stdlib", "io-tokio", "io-axum", "jiff"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
rust-mcp-schema = { version = "2", default-features = false, features = ["2025_11_25", "schema_utils"] }
schemars = "1.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
jiff = { version = "0.2", features = ["serde"], optional = true }
chrono = { version = "0.4", features = ["serde"], optional = true }
base64 = "0.22"
thiserror = "2.0"
tokio = { version = "1", features = ["io-std", "io-util", "sync"], optional = true }
tracing = "0.1"
axum = { version = "0.8", optional = true }
rand = { version = "0.9", optional = true }
clap = { version = "4", features = ["string"], optional = true }

[dev-dependencies]
insta = { version = "=1.46.3", features = ["filters"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
tower = { version = "0.5", features = ["util"] }
tempfile = "3"
